// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQssxm9uts2aTI8GCyD0waeb2yQgeQjQ8',
    appId: '1:568278540801:web:d3496828cd3ff7f4065600',
    messagingSenderId: '568278540801',
    projectId: 'mobile-kombat',
    authDomain: 'mobile-kombat.firebaseapp.com',
    databaseURL: 'https://mobile-kombat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-kombat.appspot.com',
    measurementId: 'G-N83F1Q2QV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByQwpOHXICPMgq3r-UYohba5kabC9W2Tc',
    appId: '1:568278540801:android:857287c9288e3e09065600',
    messagingSenderId: '568278540801',
    projectId: 'mobile-kombat',
    databaseURL: 'https://mobile-kombat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-kombat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8otuQ3tKh8Z8XZBpNOZfIeM8mZkiWoLc',
    appId: '1:568278540801:ios:61d9fc13353c1afe065600',
    messagingSenderId: '568278540801',
    projectId: 'mobile-kombat',
    databaseURL: 'https://mobile-kombat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-kombat.appspot.com',
    iosClientId: '568278540801-dnu9don3ji9401obv33uuqvcnm4v1dvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8otuQ3tKh8Z8XZBpNOZfIeM8mZkiWoLc',
    appId: '1:568278540801:ios:61d9fc13353c1afe065600',
    messagingSenderId: '568278540801',
    projectId: 'mobile-kombat',
    databaseURL: 'https://mobile-kombat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-kombat.appspot.com',
    iosClientId: '568278540801-dnu9don3ji9401obv33uuqvcnm4v1dvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
